using RePattern.Common.Enums;
using RePattern.Domain.Entities;

namespace RePattern.Data.Database.Seeders
{
    public class TestQuestionSeeder : IDataSeeder
    {
        public void Seed(ApplicationDbContext context)
        {
            if (context.TestQuestions.Any())
                return;

            var testQuestions = new List<TestQuestion>
            {
                //Sneak into basket
                new() { Id = 10, Description = "The \"Sneak into Basket\" deceptive pattern places unwanted products or services into the shopping cart?", Hint = "See the deceptive pattern's name.", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 2 },
                new() { Id = 20, Description = "The \"Sneak into Basket\" deceptive pattern manipulates through \"double negatives\" or \"inversion of choices\"?", Hint = "See the deceptive pattern's name.", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 2 },
                new() { Id = 30, Description = "The \"Sneak into Basket\" deceptive pattern forces users to buy extra products?", Hint = "Can users remove extra products?", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 2, Explanation = "The \"Sneak into Basket\" deceptive pattern sneaks products or services into the shopping cart, but allows consumers to remove them." },
                new() { Id = 40, Description = "Which of these deceptive patterns is the \"Sneak into basket\" one?", Hint = "Which picture shows an extra unwanted product added to the cart?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 2, ImageURL = "/images/tests/sneak-into-basket/select_1.png", Explanation = "Number 2 as it shows an extra product in the cart - \"Forever Sports magazine\"."},
                new() { Id = 50, Description = "Would this be categorized as the \"Sneak into basket\" deceptive pattern?", Hint = "Is the added product quantity larger than 0?", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 2, ImageURL = "/images/tests/sneak-into-basket/choose_1.png"},
                new() { Id = 60, Description = "Which deceptive pattern is shown in the picture?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SHORT_TEXT, ShortText = "sneak into basket", TestId = 2, ImageURL = "/images/tests/sneak-into-basket/short_1.png"},
                new() { Id = 70, Description = "Select all characteristics of the \"Sneak into basket\" deceptive pattern?", Hint = "Sneaks products and is not forceful, but nudges.", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.MULTI_SELECT, ShortText = null, TestId = 2},

                //Hidden costs
                new() { Id = 80, Description = "The \"Hidden costs\" deceptive pattern promises an initial lower price, which later increases?", Hint = "See the deceptive pattern's name.", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 3 },
                new() { Id = 90, Description = "The \"Hidden costs\" deceptive pattern often justifies extra costs as \"service fees\" or \"delivery costs\"?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 3 },
                new() { Id = 100, Description = "The \"Hidden costs\" deceptive pattern uses confusing or overwhelming visuals?", Hint = "Think about what does the \"Visual interference\" pattern do?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 3 },
                new() { Id = 110, Description = "Costs, revealed later, always constitute the \"Hidden costs\" deceptive pattern?", Hint = "Can I calculate the shipping costs before checkout if I don\'t know the destination yet?", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 3, Explanation = "Some costs can only be calculated later during the checkout process. For example, users may choose different shipping options, which vary in price." },
                new() { Id = 120, Description = "Which deceptive pattern is shown in the picture?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SHORT_TEXT, ShortText = "hidden costs", TestId = 3, ImageURL = "/images/tests/hidden-costs/short_1.png"},
                new() { Id = 130, Description = "Select all characteristics of the \"Hidden costs\" deceptive pattern?", Hint = "Inflates the price at the end of the checkout process.", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.MULTI_SELECT, ShortText = null, TestId = 3},
                new() { Id = 140, Description = "Which of these deceptive patterns is the \"Hidden costs\" one?", Hint = "Which picture shows an extra unwanted / hidden costs added to the cart?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 3, ImageURL = "/images/tests/hidden-costs/select_1.png", Explanation = "Number 3 as it shows an extra hidden costs, such as a \"Convenience charge\"."},

                //Hidden subscription
                new() { Id = 150, Description = "The \"Hidden subscription\" deceptive pattern secretly enrolls the user into a subscription?", Hint = "See the deceptive pattern's name.", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 4 },
                new() { Id = 160, Description = "The \"Hidden subscription\" deceptive pattern may use wording like \"free trial\" or \"one-time payment\" to entice users?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 4 },
                new() { Id = 170, Description = "The \"Hidden subscription\" deceptive pattern's main characteristic is that the sneaky subscription is hard to cancel?", Hint = "This is a primary characteristic of another deceptive pattern.", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 4, Explanation = "Even though the subscription is started sneakily or without explicit consent, it may still be easy to cancel." },
                new() { Id = 180, Description = "Which deceptive pattern is shown in the picture?", Hint = "Is it clear what happens after the 30 day free trial?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SHORT_TEXT, ShortText = "hidden subscription", TestId = 4, ImageURL = "/images/tests/hidden-subscription/short_1.png", Explanation = "The advertisement does not disclose what happens after the 30 day trial and that it starts a subscription automatically."},
                new() { Id = 190, Description = "Select all characteristics of the \"Hidden subscription\" deceptive pattern?", Hint = "Sneakily enrolls the user into a subscription.", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.MULTI_SELECT, ShortText = null, TestId = 4},
                new() { Id = 200, Description = "Which of these deceptive patterns is the \"Hidden subscription\" one?", Difficulty = TestQuestionDifficultyEnum.HARD, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 4, ImageURL = "/images/tests/hidden-subscription/select_1.png", Explanation = "1 - Sneak into basket, 2 - Activity message, 3 - Pressured selling"},

                //Limited time message
                new() { Id = 210, Description = "The \"Limited time message\" deceptive pattern informs users that certain products or offers will be available for a limited time, but does not disclose the exact deadline?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 5 },
                new() { Id = 220, Description = "The \"Limited time message\" deceptive pattern may use wording like \"soon\" or \"shortly\" among others?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 5 },
                new() { Id = 230, Description = "If an exact offer deadline is disclosed using a countdown, then the user interface element will not be deceptive?", Hint = "Does the countdown urge users to buy the product? Is it actually real?", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 5, Explanation = "Countdowns may indicate the \"Countdown timer\" deceptive pattern. They often urge users to buy a certain product, or display left time fraudulently, simply refreshing it, when the countdown ends." },
                new() { Id = 240, Description = "Which deceptive pattern is shown in the picture?", Hint = "Is the exact offer deadline disclosed?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SHORT_TEXT, ShortText = "limited time message", TestId = 5, ImageURL = "/images/tests/limited-time-message/short_1.png", Explanation = "The sale banner does not include the exact offer end date."},
                new() { Id = 250, Description = "Select all characteristics of the \"Limited time message\" deceptive pattern?", Hint = "Does not disclose the exact offer deadline.", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.MULTI_SELECT, ShortText = null, TestId = 5},
                new() { Id = 260, Description = "Which of these deceptive patterns is the \"Limited time message\" one?", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 5, ImageURL = "/images/tests/limited-time-message/select_1.png", Explanation = "Number 1 informs that the spring sale is ending soon, but does not disclose the exact date."},

                //Confirmshaming
                new() { Id = 270, Description = "The \"Confirmshaming\" deceptive pattern employs language, aiming to elicit a negative emotional response, like \"guilt\" or \"shame\"?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 6 },
                new() { Id = 280, Description = "The \"Confirmshaming\" deceptive pattern may word notifications in a self-destructive or condescending way?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 6 },
                new() { Id = 290, Description = "The \"Confirmshaming\" deceptive patterns main characteristic is that it forces users to complete unnecessary actions?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 6, Explanation = "The \"Confirmshaming\" deceptive pattern is not forceful, but aims to sway users into selecting / not selecting certain options through emotional means." },
                new() { Id = 300, Description = "Which deceptive pattern is shown in the picture?", Hint = "Is the wording in the picture respectful? Does it sway the user to not select the discount option?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SHORT_TEXT, ShortText = "confirmshaming", TestId = 6, ImageURL = "/images/tests/confirmshaming/short_1.png", Explanation = "The option to not get a discount - \"I like full price\" - elicits a negative emotional response and talks to the user in a condescending way."},
                new() { Id = 310, Description = "Select all characteristics of the \"Confirmshaming\" deceptive pattern?", Hint = "Elicits a negative emotional response and is often condescending to the user.", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.MULTI_SELECT, ShortText = null, TestId = 6},
                new() { Id = 320, Description = "Which of these deceptive patterns is the \"Confirmshaming\" one?", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 6, ImageURL = "/images/tests/confirmshaming/select_1.png", Explanation = "Number 4 uses condescending wording, which the user has to click, if they do not want to receive the discount."},

                //Visual interference
                new() { Id = 330, Description = "The \"Visual interference\" deceptive pattern often uses presentation and style in order to sway users into making or avoiding certain actions?", Hint = "See the deceptive pattern's name.", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 7 },
                new() { Id = 340, Description = "The \"Visual interference\" deceptive pattern may place information in unexpected places, overwhelm the user interface, use a small font with low contrast?", Hint = "See the deceptive pattern's name.", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 7 },
                new() { Id = 350, Description = "\"Visual interference\" is one of the most versatile deceptive patterns?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 7, Explanation = "Presentation and style, which is deceptively manipulated by this pattern, may be employed in many different ways." },
                new() { Id = 360, Description = "Which deceptive pattern is shown in the picture?", Hint = "Are some user interface elements deliberately more hidden?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SHORT_TEXT, ShortText = "visual interference", TestId = 7, ImageURL = "/images/tests/visual-interference/short_1.png", Explanation = "Low contrast and small font size are deliberately used so users miss that upgrades are non refundable"},
                new() { Id = 370, Description = "Select all characteristics of the \"Visual interference\" deceptive pattern?", Hint = "Uses presentation and style to manipulatively influence user decisions.", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.MULTI_SELECT, ShortText = null, TestId = 7},
                new() { Id = 380, Description = "Which of these deceptive patterns is the \"Visual interference\" one?", Hint = "Is the grayed out option actually unavailable?", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 7, ImageURL = "/images/tests/visual-interference/select_1.png", Explanation = "Number 1 makes it seem like the cheapest subscription option is unavailable (grayed out), when in fact, it is."},

                //Trick questions
                new() { Id = 390, Description = "The \"Trick questions\" deceptive pattern employs confusing language and exploits consumer expectations?", Hint = "See the deceptive pattern's name.", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 8 },
                new() { Id = 400, Description = "The \"Trick questions\" deceptive pattern uses techniques like \"double negatives\" or \"inversion of choices\"?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 8 },
                new() { Id = 410, Description = "The \"Trick questions\" always uses pre-selection?", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 8, Explanation = "Options may not be always selected. For example, by using \"inversion of choices\" - \"check not to receive\"." },
                new() { Id = 420, Description = "Which deceptive pattern is shown in the picture?", Hint = "Is the check mark prompt easily understandable and straightforward?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SHORT_TEXT, ShortText = "trick questions", TestId = 8, ImageURL = "/images/tests/trick-questions/short_1.png", Explanation = "The check mark prompt employs the \"inversion of choices\" technique, where users have to tick a box to decline certain options instead of it being a direct opt-in."},
                new() { Id = 430, Description = "Select all characteristics of the \"Trick questions\" deceptive pattern?", Hint = "Uses wording techniques, that are confusing and not within the consumer expectations.", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.MULTI_SELECT, ShortText = null, TestId = 8},
                new() { Id = 440, Description = "Which of these deceptive patterns is the \"Trick questions\" one?", Hint = "Which example uses reverse and confusing wording?", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 8, ImageURL = "/images/tests/trick-questions/select_1.png", Explanation = "Number 2 check mark prompt employs the \"inversion of choices\" technique, where users have to tick a box to decline certain options instead of it being a direct opt-in."},

                //Hard to cancel
                new() { Id = 450, Description = "The \"Hard to cancel\" deceptive pattern provides consumers with an easy way of enrolling into a certain service, but makes it hard to cancel it?", Hint = "See the deceptive pattern's name.", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 9 },
                new() { Id = 460, Description = "The \"Hard to cancel\" deceptive pattern may use slogans like \"Cancel anytime\", while the actual cancellation policies and means may be obscured?", Hint = "See the deceptive pattern's name.", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 9 },
                new() { Id = 470, Description = "The \"Hard to cancel\" deceptive pattern employs confusing language and exploits consumer expectations?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 9, Explanation = "This aspect is indicative of the \"Trick questions\" deceptive pattern." },
                new() { Id = 480, Description = "Which deceptive pattern is shown in the picture?", Hint = "How easy is the cancellation process?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SHORT_TEXT, ShortText = "hard to cancel", TestId = 9, ImageURL = "/images/tests/hard-to-cancel/short_1.png", Explanation = "The cancellation process is quite hard, requiring users to call customer service, instead of doing it online."},
                new() { Id = 490, Description = "Select all characteristics of the \"Hard to cancel\" deceptive pattern?", Hint = "Makes it hard to cancel services or subscriptions.", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.MULTI_SELECT, ShortText = null, TestId = 9},
                new() { Id = 500, Description = "Which of these deceptive patterns is the \"Hard to cancel\" one?", Hint = "Which example makes it hard to FULLY cancel services or subscriptions?", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 9, ImageURL = "/images/tests/hard-to-cancel/select_1.png", Explanation = "Number 1 makes it seem that by pressing \"Yes\", all marketing emails will be cancelled in the future. However, the full cancellation process in only available if the user presses on the link below."},

                //Forced enrollment
                new() { Id = 510, Description = "The \"Forced enrollment\" deceptive pattern coerces users to perform additional unwanted or unrelated tasks?", Hint = "See the deceptive pattern's name.", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 10 },
                new() { Id = 520, Description = "The goal of the \"Forced enrollment\" deceptive pattern quite often is to forcefully collect valuable user information?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 10 },
                new() { Id = 530, Description = "The \"Forced enrollment\" deceptive pattern places unwanted products or services into the shopping cart?", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 10, Explanation = "This aspect is indicative of the \"Sneak into basket\" deceptive pattern." },
                new() { Id = 540, Description = "Which deceptive pattern is shown in the picture?", Hint = "It forces users to register.", Difficulty = TestQuestionDifficultyEnum.EASY, Type = TestQuestionTypeEnum.SHORT_TEXT, ShortText = "forced enrollment", TestId = 10, ImageURL = "/images/tests/forced-enrollment/short_1.png", Explanation = "Users must sign in or register before they can make a purchase."},
                new() { Id = 550, Description = "Select all characteristics of the \"Forced enrollment\" deceptive pattern?", Hint = "Coerces users to perform additional unwanted or unrelated tasks.", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.MULTI_SELECT, ShortText = null, TestId = 10},
                new() { Id = 560, Description = "Which of these deceptive patterns is the \"Forced enrollment\" one?", Hint = "Which example forces the user to disclose personal information?", Difficulty = TestQuestionDifficultyEnum.NORMAL, Type = TestQuestionTypeEnum.SINGLE_SELECT, ShortText = null, TestId = 10, ImageURL = "/images/tests/forced-enrollment/select_1.png", Explanation = "Number 1 forces users to import their address book, even though it should not be required."},
            };

            SeederSqlServerHelper.SeedWithIdentityInsert(context, "TestQuestion", context.TestQuestions, testQuestions);
        }
    }
}
